version: '3.6'
services:
  mysqldb:
    image: 'mysql:latest'
    container_name: 'hw_13_webapp'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'hw_13_webapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - hw_13:/var/lib/mysql
volumes:
  hw_13:
